### ISSUE TITLE
Update CA-certificates

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#22]
We should do the same, what LineageOS has done in the KitKat branch (cm-11.0), see here:
https://review.lineageos.org/#/q/topic:cacerts

This gets rid of outdated (and potentially insecure) certificates and takes the most recent from the AOSP project (we should even track the 'master' branch, as internally discussed)

**Comment by Micha-Btz** [comment]
Makes sense to me. Let's do it.

**Comment by MSe1969** [comment]
Applied to test branch, did a test build, looks OK.
Please also test on your end. I am not using GApps, a test with GApps should also take place.

**Comment by hahnjo** [comment]
I still can't help much, didn't hear back from the Ubuntu team so I think my VM is still not working...

**Comment by Micha-Btz** [comment]
@hahnjo where is your problem with that?

@MSe1969 running test build since Saturday without problems.

**Comment by hahnjo** [comment]
@Micha-Btz I got kernel oops' when building, probably because I'm using NFS to mount my host's directories with the sources. However, yesterday's build went fine, fingers crossed that it's really fixed.

I'm currently running with the updated certificates (and GApps) and haven't found a problem so far.

**Comment by MSe1969** [comment]
Thanks for testing on your end - works fine with my device, too. Closing this issue, we'll ship together with March ASB patches
