### ISSUE TITLE
Backport CVE-2020-0096 (aka "StrandHogg 2.0") from May 2020 ASB

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#69]
CVE-2020-0096 was too quickly flagged as "not applicable" for Android 5.1 - the code in question indeed is located indeed in different Java classes, hence a backport is required.

**Comment by MSe1969** [comment]
Pushed backport to frameworks/base (branch cm-12.1-test)
@foresto - would you mind taking a look at the back port for CVE-2020-0096 (last two commits in frameworks/base, branch cm-12.1-test) and tell me your thoughts?

**Comment by foresto** [comment]
cm12-amami/android_frameworks_base@18cdb91aff39b9df6383d3467038654270fa01ac looks sane to me.

cm12-amami/android_frameworks_base@f640970c68c6c772dd0ea033b6d9eb4b56b7953d looks like it would compile, but without knowing what passes `incomingRealCallingUid` in modern Android, I can't tell whether the security patch will be effective in Lollipop.

If that argument is only passed by other ActivityManager components in modern Android, and the call chains aren't complicated, it might make sense to [add support for it](https://android.googlesource.com/platform/frameworks/base/+/d37eb96212c6fe4819c66bd0a1e0a2f9f7501602/services/core/java/com/android/server/am/ActivityStarter.java#905). On the other hand, perhaps that's outside the scope of this life support project. I think you're going to have to make this judgment call, since my amami device finally died. :(

**Comment by MSe1969** [comment]
Pitty your Z1c died - nevertheless, thanks for the feedback! Seems you had the same thoughts than me. I've asked myself the same question and tried to follow the call-chain.

Looking at Oreo for example, seems that key is to backport this commit:
https://android.googlesource.com/platform/frameworks/base/+/dcd427cceec17ace13a1808a94bbe1961272277

I'll have a look, maybe you're right and it will be worth the effort . . .

**Comment by MSe1969** [comment]
OK, commit backported and newly pushed to cm-12.1-test

**Comment by MSe1969** [comment]
Tested successfully (by means of: "no regression") - will be made part of June build
